// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	types "dengovie/internal/service/debts/types"

	mock "github.com/stretchr/testify/mock"
)

// MockDebtsService is an autogenerated mock type for the DebtsService type
type MockDebtsService struct {
	mock.Mock
}

type MockDebtsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDebtsService) EXPECT() *MockDebtsService_Expecter {
	return &MockDebtsService_Expecter{mock: &_m.Mock}
}

// ShareDebt provides a mock function with given fields: ctx, input
func (_m *MockDebtsService) ShareDebt(ctx context.Context, input types.ShareDebtInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ShareDebt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ShareDebtInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDebtsService_ShareDebt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareDebt'
type MockDebtsService_ShareDebt_Call struct {
	*mock.Call
}

// ShareDebt is a helper method to define mock.On call
//   - ctx context.Context
//   - input types.ShareDebtInput
func (_e *MockDebtsService_Expecter) ShareDebt(ctx interface{}, input interface{}) *MockDebtsService_ShareDebt_Call {
	return &MockDebtsService_ShareDebt_Call{Call: _e.mock.On("ShareDebt", ctx, input)}
}

func (_c *MockDebtsService_ShareDebt_Call) Run(run func(ctx context.Context, input types.ShareDebtInput)) *MockDebtsService_ShareDebt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.ShareDebtInput))
	})
	return _c
}

func (_c *MockDebtsService_ShareDebt_Call) Return(_a0 error) *MockDebtsService_ShareDebt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDebtsService_ShareDebt_Call) RunAndReturn(run func(context.Context, types.ShareDebtInput) error) *MockDebtsService_ShareDebt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDebtsService creates a new instance of MockDebtsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDebtsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDebtsService {
	mock := &MockDebtsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
