disable-version-string: true
packages:
  dengovie/internal/store/types:
    config:
      dir: internal/mocks/store
    interfaces:
      Storage:
  dengovie/internal/service/debts/types:
    config:
      dir: internal/mocks/service/debts_mock
    interfaces:
      Service:
  dengovie/internal/service/users/types:
    config:
      dir: internal/mocks/service/users_mock
    interfaces:
      Service:
  dengovie/internal/service/telegram/types:
    config:
      dir: internal/mocks/service/telegram_mock
    interfaces:
      Client:
  dengovie/internal/utils/jwt/types:
    config:
      dir: internal/mocks/utils/jwt_mock
    interfaces:
      Processor:
