apiVersion: v1
data:
  .env: |-
    JWT_TOKEN="na_prikole"
    POSTGRES_CONN_STRING="postgresql://db:5432/dengovie?user=postgres&password=pass&sslmode=disable"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: backend
  name: backend-cm0
