// Code generated by mockery. DO NOT EDIT.

package types

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// SendMessageToUserByAlias provides a mock function with given fields: ctx, alias, message
func (_m *MockClient) SendMessageToUserByAlias(ctx context.Context, alias string, message string) error {
	ret := _m.Called(ctx, alias, message)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageToUserByAlias")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, alias, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_SendMessageToUserByAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageToUserByAlias'
type MockClient_SendMessageToUserByAlias_Call struct {
	*mock.Call
}

// SendMessageToUserByAlias is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
//   - message string
func (_e *MockClient_Expecter) SendMessageToUserByAlias(ctx interface{}, alias interface{}, message interface{}) *MockClient_SendMessageToUserByAlias_Call {
	return &MockClient_SendMessageToUserByAlias_Call{Call: _e.mock.On("SendMessageToUserByAlias", ctx, alias, message)}
}

func (_c *MockClient_SendMessageToUserByAlias_Call) Run(run func(ctx context.Context, alias string, message string)) *MockClient_SendMessageToUserByAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_SendMessageToUserByAlias_Call) Return(_a0 error) *MockClient_SendMessageToUserByAlias_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_SendMessageToUserByAlias_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_SendMessageToUserByAlias_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
