// Code generated by mockery. DO NOT EDIT.

package types

import (
	context "context"
	types "dengovie/internal/service/users/types"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CheckAndDeleteUser provides a mock function with given fields: ctx, input
func (_m *MockService) CheckAndDeleteUser(ctx context.Context, input types.CheckAndDeleteUserInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CheckAndDeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.CheckAndDeleteUserInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_CheckAndDeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAndDeleteUser'
type MockService_CheckAndDeleteUser_Call struct {
	*mock.Call
}

// CheckAndDeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - input types.CheckAndDeleteUserInput
func (_e *MockService_Expecter) CheckAndDeleteUser(ctx interface{}, input interface{}) *MockService_CheckAndDeleteUser_Call {
	return &MockService_CheckAndDeleteUser_Call{Call: _e.mock.On("CheckAndDeleteUser", ctx, input)}
}

func (_c *MockService_CheckAndDeleteUser_Call) Run(run func(ctx context.Context, input types.CheckAndDeleteUserInput)) *MockService_CheckAndDeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.CheckAndDeleteUserInput))
	})
	return _c
}

func (_c *MockService_CheckAndDeleteUser_Call) Return(_a0 error) *MockService_CheckAndDeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_CheckAndDeleteUser_Call) RunAndReturn(run func(context.Context, types.CheckAndDeleteUserInput) error) *MockService_CheckAndDeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
