
name: post-deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  dockerhub-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dengovie-backend:${{ github.sha }}


  deploy-backend:
    runs-on: ubuntu-latest
    requires:
      - dockerhub-backend
    steps:
      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - name: Update Deployment Image
        run: |
          kubectl set image deployments/backend dengovie-backend=wiirtex/dengovie-backend:${{ github.sha }}
          


  dockerhub-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./client-app
          file: ./client-app/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dengovie-frontend:${{ github.sha }}
