
name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis result

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for frontend analysis)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: client-app/package-lock.json

      - name: Install frontend dependencies
        working-directory: client-app
        run: npm install

      - name: Run tests with coverage (if needed)
        working-directory: client-app
        run: npm test -- --coverage

      - name: Check coverage files
        working-directory: client-app
        run: |
          ls -la
          ls -la coverage/ || echo "Coverage directory not found"
          find . -name "lcov.info" -o -name "coverage-final.json" || echo "No coverage files found"
        
      - name: Analyze with SonarCloud

        # You can pin the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@v2.2.0
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          # Additional arguments for the SonarScanner CLI
          args:
            # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            # mandatory
            -Dsonar.organization=wiirtex
            -Dsonar.qualitygate.wait=true
            -Dsonar.projectKey=wiirtex_dengovie
            -Dsonar.projectName=dengovie
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/.github/**,**/tests/**,**/venv/**,**/components/product/*.test.jsx,**/frontend/coverage/**,**Dockerfile**
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.javascript.lcov.reportPaths=client-app/coverage/lcov.info
            -Dsonar.tests=client-app/src
            -Dsonar.test.inclusions=**/*.test.jsx,**/*.test.js,**/*.test.tsx,**/*.test.ts
          
          projectBaseDir: .
